version: '3'
services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postevedb
    volumes:
      - posteve-db:/var/lib/postgresql/data

volumes:
  posteve-db: